# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import timestamp_pb2 as timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Common.proto',
  package='Seefar.Interfaces.Common',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x43ommon.proto\x12\x18Seefar.Interfaces.Common\x1a\x0ftimestamp.proto\"\x99\x01\n\rMessageHeader\x12\x31\n\x0bmessageTime\x18\x01 \x02(\x0b\x32\x1c.Seefar.Interfaces.Timestamp\x12\x19\n\nIcdVersion\x18\x02 \x02(\t:\x05\x32.6.0\x12\r\n\x05\x63\x61\x62ID\x18\x03 \x01(\x03\x12\x15\n\rmessageSource\x18\x04 \x01(\t\x12\x14\n\x0cmessageIndex\x18\x05 \x01(\x05\"\xae\x01\n\nBitMessage\x12\x37\n\x06header\x18\x01 \x02(\x0b\x32\'.Seefar.Interfaces.Common.MessageHeader\x12\x10\n\x08SourceId\x18\x02 \x02(\x05\x12:\n\tBitStatus\x18\x03 \x02(\x0e\x32\'.Seefar.Interfaces.Common.BitStatusEnum\x12\x19\n\x11\x45rrorsDescription\x18\x04 \x03(\t\"\xab\x01\n\x12SystemEventMessage\x12\x37\n\x06header\x18\x01 \x02(\x0b\x32\'.Seefar.Interfaces.Common.MessageHeader\x12\x39\n\x08Severity\x18\x02 \x02(\x0e\x32\'.Seefar.Interfaces.Common.EventSeverity\x12\x10\n\x08SourceId\x18\x03 \x02(\x05\x12\x0f\n\x07Message\x18\x04 \x02(\t\"\x1e\n\x06Offset\x12\t\n\x01X\x18\x01 \x02(\x01\x12\t\n\x01Y\x18\x02 \x02(\x01\"i\n\x0b\x42oundingBox\x12,\n\x02UL\x18\x04 \x02(\x0b\x32 .Seefar.Interfaces.Common.Offset\x12,\n\x02LR\x18\x05 \x02(\x0b\x32 .Seefar.Interfaces.Common.Offset*1\n\rBitStatusEnum\x12\x06\n\x02OK\x10\x00\x12\x0c\n\x08\x44\x65graded\x10\x01\x12\n\n\x06\x46\x61iled\x10\x02*?\n\rEventSeverity\x12\x08\n\x04Info\x10\x00\x12\x0b\n\x07Warning\x10\x01\x12\t\n\x05\x45rror\x10\x02\x12\x0c\n\x08\x43ritical\x10\x03'
  ,
  dependencies=[timestamp__pb2.DESCRIPTOR,])

_BITSTATUSENUM = _descriptor.EnumDescriptor(
  name='BitStatusEnum',
  full_name='Seefar.Interfaces.Common.BitStatusEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Degraded', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Failed', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=705,
  serialized_end=754,
)
_sym_db.RegisterEnumDescriptor(_BITSTATUSENUM)

BitStatusEnum = enum_type_wrapper.EnumTypeWrapper(_BITSTATUSENUM)
_EVENTSEVERITY = _descriptor.EnumDescriptor(
  name='EventSeverity',
  full_name='Seefar.Interfaces.Common.EventSeverity',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Info', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Warning', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Error', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Critical', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=756,
  serialized_end=819,
)
_sym_db.RegisterEnumDescriptor(_EVENTSEVERITY)

EventSeverity = enum_type_wrapper.EnumTypeWrapper(_EVENTSEVERITY)
OK = 0
Degraded = 1
Failed = 2
Info = 0
Warning = 1
Error = 2
Critical = 3



_MESSAGEHEADER = _descriptor.Descriptor(
  name='MessageHeader',
  full_name='Seefar.Interfaces.Common.MessageHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageTime', full_name='Seefar.Interfaces.Common.MessageHeader.messageTime', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='IcdVersion', full_name='Seefar.Interfaces.Common.MessageHeader.IcdVersion', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=b"2.6.0".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cabID', full_name='Seefar.Interfaces.Common.MessageHeader.cabID', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messageSource', full_name='Seefar.Interfaces.Common.MessageHeader.messageSource', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messageIndex', full_name='Seefar.Interfaces.Common.MessageHeader.messageIndex', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=213,
)


_BITMESSAGE = _descriptor.Descriptor(
  name='BitMessage',
  full_name='Seefar.Interfaces.Common.BitMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='Seefar.Interfaces.Common.BitMessage.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SourceId', full_name='Seefar.Interfaces.Common.BitMessage.SourceId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BitStatus', full_name='Seefar.Interfaces.Common.BitMessage.BitStatus', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ErrorsDescription', full_name='Seefar.Interfaces.Common.BitMessage.ErrorsDescription', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=390,
)


_SYSTEMEVENTMESSAGE = _descriptor.Descriptor(
  name='SystemEventMessage',
  full_name='Seefar.Interfaces.Common.SystemEventMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='Seefar.Interfaces.Common.SystemEventMessage.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Severity', full_name='Seefar.Interfaces.Common.SystemEventMessage.Severity', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SourceId', full_name='Seefar.Interfaces.Common.SystemEventMessage.SourceId', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Message', full_name='Seefar.Interfaces.Common.SystemEventMessage.Message', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=564,
)


_OFFSET = _descriptor.Descriptor(
  name='Offset',
  full_name='Seefar.Interfaces.Common.Offset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='Seefar.Interfaces.Common.Offset.X', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Y', full_name='Seefar.Interfaces.Common.Offset.Y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=566,
  serialized_end=596,
)


_BOUNDINGBOX = _descriptor.Descriptor(
  name='BoundingBox',
  full_name='Seefar.Interfaces.Common.BoundingBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='UL', full_name='Seefar.Interfaces.Common.BoundingBox.UL', index=0,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LR', full_name='Seefar.Interfaces.Common.BoundingBox.LR', index=1,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=703,
)

_MESSAGEHEADER.fields_by_name['messageTime'].message_type = timestamp__pb2._TIMESTAMP
_BITMESSAGE.fields_by_name['header'].message_type = _MESSAGEHEADER
_BITMESSAGE.fields_by_name['BitStatus'].enum_type = _BITSTATUSENUM
_SYSTEMEVENTMESSAGE.fields_by_name['header'].message_type = _MESSAGEHEADER
_SYSTEMEVENTMESSAGE.fields_by_name['Severity'].enum_type = _EVENTSEVERITY
_BOUNDINGBOX.fields_by_name['UL'].message_type = _OFFSET
_BOUNDINGBOX.fields_by_name['LR'].message_type = _OFFSET
DESCRIPTOR.message_types_by_name['MessageHeader'] = _MESSAGEHEADER
DESCRIPTOR.message_types_by_name['BitMessage'] = _BITMESSAGE
DESCRIPTOR.message_types_by_name['SystemEventMessage'] = _SYSTEMEVENTMESSAGE
DESCRIPTOR.message_types_by_name['Offset'] = _OFFSET
DESCRIPTOR.message_types_by_name['BoundingBox'] = _BOUNDINGBOX
DESCRIPTOR.enum_types_by_name['BitStatusEnum'] = _BITSTATUSENUM
DESCRIPTOR.enum_types_by_name['EventSeverity'] = _EVENTSEVERITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageHeader = _reflection.GeneratedProtocolMessageType('MessageHeader', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEHEADER,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:Seefar.Interfaces.Common.MessageHeader)
  })
_sym_db.RegisterMessage(MessageHeader)

BitMessage = _reflection.GeneratedProtocolMessageType('BitMessage', (_message.Message,), {
  'DESCRIPTOR' : _BITMESSAGE,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:Seefar.Interfaces.Common.BitMessage)
  })
_sym_db.RegisterMessage(BitMessage)

SystemEventMessage = _reflection.GeneratedProtocolMessageType('SystemEventMessage', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMEVENTMESSAGE,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:Seefar.Interfaces.Common.SystemEventMessage)
  })
_sym_db.RegisterMessage(SystemEventMessage)

Offset = _reflection.GeneratedProtocolMessageType('Offset', (_message.Message,), {
  'DESCRIPTOR' : _OFFSET,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:Seefar.Interfaces.Common.Offset)
  })
_sym_db.RegisterMessage(Offset)

BoundingBox = _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), {
  'DESCRIPTOR' : _BOUNDINGBOX,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:Seefar.Interfaces.Common.BoundingBox)
  })
_sym_db.RegisterMessage(BoundingBox)


# @@protoc_insertion_point(module_scope)
