# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GisData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import timestamp_pb2 as timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='GisData.proto',
  package='Seefar.Interfaces.Gis',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rGisData.proto\x12\x15Seefar.Interfaces.Gis\x1a\x0ftimestamp.proto\">\n\tGeoOffset\x12\x0f\n\x07OffsetX\x18\x01 \x01(\x01\x12\x0f\n\x07OffsetY\x18\x02 \x01(\x01\x12\x0f\n\x07OffsetZ\x18\x03 \x01(\x01\"6\n\x08GeoPoint\x12\x0b\n\x03Lat\x18\x01 \x01(\x01\x12\x0b\n\x03Lon\x18\x02 \x01(\x01\x12\x10\n\x08\x41ltitude\x18\x03 \x01(\x01\"j\n\nGisSegment\x12.\n\x05start\x18\x01 \x01(\x0b\x32\x1f.Seefar.Interfaces.Gis.GeoPoint\x12,\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x1f.Seefar.Interfaces.Gis.GeoPoint\"|\n\x11GisSegmentsReport\x12\x31\n\x0bmessageTime\x18\x01 \x01(\x0b\x32\x1c.Seefar.Interfaces.Timestamp\x12\x34\n\tRouteData\x18\x02 \x03(\x0b\x32!.Seefar.Interfaces.Gis.GisSegmentb\x06proto3'
  ,
  dependencies=[timestamp__pb2.DESCRIPTOR,])




_GEOOFFSET = _descriptor.Descriptor(
  name='GeoOffset',
  full_name='Seefar.Interfaces.Gis.GeoOffset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='OffsetX', full_name='Seefar.Interfaces.Gis.GeoOffset.OffsetX', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OffsetY', full_name='Seefar.Interfaces.Gis.GeoOffset.OffsetY', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OffsetZ', full_name='Seefar.Interfaces.Gis.GeoOffset.OffsetZ', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=119,
)


_GEOPOINT = _descriptor.Descriptor(
  name='GeoPoint',
  full_name='Seefar.Interfaces.Gis.GeoPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Lat', full_name='Seefar.Interfaces.Gis.GeoPoint.Lat', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Lon', full_name='Seefar.Interfaces.Gis.GeoPoint.Lon', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Altitude', full_name='Seefar.Interfaces.Gis.GeoPoint.Altitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=175,
)


_GISSEGMENT = _descriptor.Descriptor(
  name='GisSegment',
  full_name='Seefar.Interfaces.Gis.GisSegment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='Seefar.Interfaces.Gis.GisSegment.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='Seefar.Interfaces.Gis.GisSegment.end', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=283,
)


_GISSEGMENTSREPORT = _descriptor.Descriptor(
  name='GisSegmentsReport',
  full_name='Seefar.Interfaces.Gis.GisSegmentsReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageTime', full_name='Seefar.Interfaces.Gis.GisSegmentsReport.messageTime', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RouteData', full_name='Seefar.Interfaces.Gis.GisSegmentsReport.RouteData', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=409,
)

_GISSEGMENT.fields_by_name['start'].message_type = _GEOPOINT
_GISSEGMENT.fields_by_name['end'].message_type = _GEOPOINT
_GISSEGMENTSREPORT.fields_by_name['messageTime'].message_type = timestamp__pb2._TIMESTAMP
_GISSEGMENTSREPORT.fields_by_name['RouteData'].message_type = _GISSEGMENT
DESCRIPTOR.message_types_by_name['GeoOffset'] = _GEOOFFSET
DESCRIPTOR.message_types_by_name['GeoPoint'] = _GEOPOINT
DESCRIPTOR.message_types_by_name['GisSegment'] = _GISSEGMENT
DESCRIPTOR.message_types_by_name['GisSegmentsReport'] = _GISSEGMENTSREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeoOffset = _reflection.GeneratedProtocolMessageType('GeoOffset', (_message.Message,), {
  'DESCRIPTOR' : _GEOOFFSET,
  '__module__' : 'GisData_pb2'
  # @@protoc_insertion_point(class_scope:Seefar.Interfaces.Gis.GeoOffset)
  })
_sym_db.RegisterMessage(GeoOffset)

GeoPoint = _reflection.GeneratedProtocolMessageType('GeoPoint', (_message.Message,), {
  'DESCRIPTOR' : _GEOPOINT,
  '__module__' : 'GisData_pb2'
  # @@protoc_insertion_point(class_scope:Seefar.Interfaces.Gis.GeoPoint)
  })
_sym_db.RegisterMessage(GeoPoint)

GisSegment = _reflection.GeneratedProtocolMessageType('GisSegment', (_message.Message,), {
  'DESCRIPTOR' : _GISSEGMENT,
  '__module__' : 'GisData_pb2'
  # @@protoc_insertion_point(class_scope:Seefar.Interfaces.Gis.GisSegment)
  })
_sym_db.RegisterMessage(GisSegment)

GisSegmentsReport = _reflection.GeneratedProtocolMessageType('GisSegmentsReport', (_message.Message,), {
  'DESCRIPTOR' : _GISSEGMENTSREPORT,
  '__module__' : 'GisData_pb2'
  # @@protoc_insertion_point(class_scope:Seefar.Interfaces.Gis.GisSegmentsReport)
  })
_sym_db.RegisterMessage(GisSegmentsReport)


# @@protoc_insertion_point(module_scope)
